
- name: Install all Logstash dependencies
  apt:
    pkg:
      - apt-transport-https
      - gnupg
    state: present

- name: Get the Elastic GPG Key
  shell: |
    curl -fsSL  https://artifacts.elastic.co/GPG-KEY-elasticsearch | apt-key add -

- name: Add the Elastic repository
  ansible.builtin.apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/8.x/apt stable main"
    state: present

- name: Index the new repository into the cache
  apt:
    name: logstash
    state: present
    update_cache: yes

- name: Create the Logstash directory
  ansible.builtin.file:
    path: /opt/logstash
    state: directory

- name: Deploy the Logstash service configuration
  ansible.builtin.template:
    src: '{{ playbook_dir }}/../templates/elastic/logstash/logstash.yml.j2'
    dest: /etc/logstash/logstash.yml
  
- name: Deploy the Logstash runtime configuration
  ansible.builtin.template:
    src: '{{ playbook_dir }}/../templates/elastic/logstash/logstash.conf.j2'
    dest: /opt/logstash/logstash.conf

