
- name: Install all Logstash dependencies
  apt:
    pkg:
      - apt-transport-https
      - gnupg
    state: present

- name: Get the Elastic GPG Key
  shell: |
    curl -fsSL  https://artifacts.elastic.co/GPG-KEY-elasticsearch | apt-key add -

- name: Add the Elastic repository
  ansible.builtin.apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/8.x/apt stable main"
    state: present

- name: Index the new repository into the cache
  apt:
    name: logstash
    state: present
    update_cache: yes

