
- name: Install Apache2
  apt: 
    name: apache2
    state: latest
    update_cache: true

- name: Install Apache2 modifications
  shell: |
    a2enmod rewrite proxy proxy_http ssl proxy_html headers

- name: Disable Apache2 compression
  shell: |
    a2dismod deflate -f

- name: Start Apache2
  ansible.builtin.service:
    name: apache2
    state: started
  
- name: Change Apache2 config to allow for mod-rewrite
  ansible.builtin.replace:
    path: /etc/apache2/apache2.conf
    after: '<Directory /var/www/>'
    before: '</Directory>'
    regexp: ^\tAllowOverride None$
    replace: '\tAllowOverride All'
  
- name: Restart the Apache service
  ansible.builtin.service:
    name: apache2
    state: restarted
