
- name: Create the Nebula directory
  ansible.builtin.file:
    path: /opt/nebula
    state: directory

- name: Get the Nebula package from GitHub
  ansible.builtin.get_url:
    url: https://github.com/slackhq/nebula/releases/download/v1.5.2/nebula-linux-amd64.tar.gz
    dest: /opt/nebula

- name: Extract the Nebula package
  ansible.builtin.unarchive:
    src: /opt/nebula/nebula-linux-amd64.tar.gz
    dest: /opt/nebula
    remote_src: true
  