
- name: Install all Docker dependencies
  apt:
    pkg:
      - ca-certificates
      - gpg
      - gnupg
      - lsb-release
      - curl
    state: present

- name: Remove the Docker GPG apt key if present (need to or next step fails)
  ansible.builtin.file:
    path: "/usr/share/keyrings/docker-archive-keyring.gpg"
    state: absent

- name: Add Docker GPG apt Key
  shell: |
    curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

- name: Add the Docker official repository for Debian to APT repos
  shell: |
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: Install Docker and all Docker Plugins
  apt: 
    pkg:
      - docker-ce
      - docker-ce-cli 
      - containerd.io 
      - docker-compose-plugin
    state: latest
    update_cache: yes


- name: Set the UFW config to govern docker routing (or else firewall rules will fail for docker containers)
  ansible.builtin.copy:
    dest: /etc/ufw/after.rules
    content: |
      # Don't delete these required lines, otherwise there will be errors
      *filter
      :ufw-after-input - [0:0]
      :ufw-after-output - [0:0]
      :ufw-after-forward - [0:0]
      # End required lines

      # don't log noisy services by default
      -A ufw-after-input -p udp --dport 137 -j ufw-skip-to-policy-input
      -A ufw-after-input -p udp --dport 138 -j ufw-skip-to-policy-input
      -A ufw-after-input -p tcp --dport 139 -j ufw-skip-to-policy-input
      -A ufw-after-input -p tcp --dport 445 -j ufw-skip-to-policy-input
      -A ufw-after-input -p udp --dport 67 -j ufw-skip-to-policy-input
      -A ufw-after-input -p udp --dport 68 -j ufw-skip-to-policy-input

      # don't log noisy broadcast
      -A ufw-after-input -m addrtype --dst-type BROADCAST -j ufw-skip-to-policy-input

      ####### BEGIN UFW AND DOCKER #######
      *filter
      :ufw-user-forward - [0:0]
      :DOCKER-USER - [0:0]
      -A DOCKER-USER -j RETURN -s 10.0.0.0/8
      -A DOCKER-USER -j RETURN -s 172.16.0.0/12
      -A DOCKER-USER -j RETURN -s 192.168.0.0/16
      -A DOCKER-USER -j ufw-user-forward
      -A DOCKER-USER -j DROP -p tcp -m tcp --tcp-flags FIN,SYN,RST,ACK SYN -d 192.168.0.0/16
      -A DOCKER-USER -j DROP -p tcp -m tcp --tcp-flags FIN,SYN,RST,ACK SYN -d 10.0.0.0/8
      -A DOCKER-USER -j DROP -p tcp -m tcp --tcp-flags FIN,SYN,RST,ACK SYN -d 172.16.0.0/12
      -A DOCKER-USER -j DROP -p udp -m udp --dport 0:32767 -d 192.168.0.0/16
      -A DOCKER-USER -j DROP -p udp -m udp --dport 0:32767 -d 10.0.0.0/8
      -A DOCKER-USER -j DROP -p udp -m udp --dport 0:32767 -d 172.16.0.0/12
      -A DOCKER-USER -j RETURN
      # END UFW AND DOCKER

      # don't delete the 'COMMIT' line or these rules won't be processed
      COMMIT