
- name: Install all Elastic dependencies
  apt:
    pkg:
      - apt-transport-https
      - curl
    state: present
    update_cache: true

- name: Get the Elastic GPG Key
  shell: |
    curl -fsSL  https://artifacts.elastic.co/GPG-KEY-elasticsearch | apt-key add -

- name: Add the Elastic repository
  ansible.builtin.apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/8.x/apt stable main"
    state: present

- name: Install Elastic and Kibana
  apt:
    pkg: 
      - elasticsearch
      - kibana
    update_cache: yes
