################################# Terry Docker Compose #################################

# This is a standard Docker Compose file except for the presence of the "required_args",
# "pre_run_commands", and "post_run_commands" which all MUST be blank if there is nothing to 
# run / no required args. The "required_args" are the required arguments to run the container
# If you have tasks you need to run, they should be VALID Ansible tasks and all Jinja templates
# MUST be escaped with [[ ]] in order to work. 

# NOTE: Jinja values that are NOT escaped are populated by Ansible at playbook init and if
# there are undefined values, Ansible will throw an error. That is important since inside of
# the ansible tasks themselves contain valid Jinja that get populated dynamically by loops

########################################################################################

services:
  cobaltstrike:
    container_name: cobaltstrike
    image: <image_path>
    command: "[[ inventory_hostname ]] [[ lookup('env', 'COBALTSTRIKE_PASSWORD') ]] /opt/cobaltstrike/mount/c2.profile"
    stdin_open: false
    tty: false
    ports:
      - "1111:50050/tcp"
      - "1443:443/tcp"
      - "180:80/tcp"
      - "153:53/udp"
    volumes:
      - type: bind
        source: /opt/container/cobaltstrike/mount
        target: /opt/cobaltstrike/mount
    # Begin invalid docker-compose (used by Terry & Ansible and stripped from file before deployment to server)
    required_args:
      - COBALTSTRIKE_PASSWORD
      - COBALTSTRIKE_MALLEABLE_C2
    pre_run_commands: 
      - name: Copy over the Malleable C2 profile (when defined)
        ansible.builtin.copy: 
          # Must escape double quotes so Jinja template is populated
          src: "[[ lookup('env', 'COBALTSTRIKE_MALLEABLE_C2') ]]"
          dest: "/opt/container/cobaltstrike/mount/c2.profile"
        when: "lookup('env', 'COBALTSTRIKE_MALLEABLE_C2') | length > 0"
      - name: Create a dummy Malleable C2 profile (when not defined)
        ansible.builtin.copy:
          dest: "/opt/container/cobaltstrike/mount/c2.profile"
          content: | 
            set sample_name "Terry";
            
            http-get {
              set uri "/itstheredteam";
              client {
                metadata {
                  netbiosu;
                  parameter "tmp";
                }
              }
              server {
                header "Content-Type" "application/octet-stream";
                output {
                  print;
                }
              }
            }
            
            http-post {
              set uri "/isittheredteam";
              client {
                header "Content-Type" "application/octet-stream";
                id {
                  uri-append;
                }
                output {
                  print;
                }
              }
              server {
                header "Content-Type" "text/html";
                output {
                  print;
                }
              }
            }
        when: "lookup('env', 'COBALTSTRIKE_MALLEABLE_C2')| length <= 0"
    post_run_commands: 

 
  deimos:
    container_name: deimos
    image: <image_path>
    stdin_open: false
    tty: false
    command: ""
    ports:
      - "2222:8443/tcp"
      - "2443:443/tcp"
      - "280:80/tcp"
      - "253:53/udp"
    volumes:
      - type: bind
        source: /opt/container/deimos/mount
        target: /opt/sliver/mount
    # Begin invalid docker-compose (used by Terry & Ansible and stripped from file before deployment to server)
    required_args:
    pre_run_commands:
    post_run_commands:


  sliver:
    container_name: sliver
    image: <image_path>
    stdin_open: false
    tty: false
    command: "daemon -p 3333"
    ports:
      - "3333:3333/tcp"
      - "3443:443/tcp"
      - "380:80/tcp"
      - "353:53/udp"
    volumes:
      - type: bind
        source: /opt/container/sliver/mount
        target: /opt/sliver/mount
    # Begin invalid docker-compose (used by Terry & Ansible and stripped from file before deployment to server)
    required_args:
    pre_run_commands:
      - name: "Delete any existing sliver configs"
        ansible.builtin.file:
          path: "/opt/container/sliver/mount/[[ old_sliver_user.value.user ]].conf"
          state: absent
        loop: "[[ team | dict2items ]]"
        loop_control:
          loop_var: old_sliver_user
          label: "[[ old_sliver_user.value.user ]]"
      - name: "Delete the sliver config for the custom sliver client"
        ansible.builtin.file:
          path: "/opt/sliver/mount/sally-sliver-siren.conf"
          state: absent
    post_run_commands:
      - name: "Generate the sliver configs for each user"
        command: "docker exec sliver /opt/sliver/sliver-server operator --lhost [[ ansible_ssh_host ]] --lport 3333 --name [[ new_sliver_user.value.user ]] --save /opt/sliver/mount/[[ new_sliver_user.value.user ]].conf"
        loop: "[[  team | dict2items ]]"
        loop_control:
          loop_var: new_sliver_user
          label: "[[ new_sliver_user.value.user ]]"
      - name: "Change ownership of each sliver config to the respective user"
        ansible.builtin.file: 
          path: "/opt/sliver/mount/[[ new_sliver_user.value.user ]].conf"
          owner: "[[ new_sliver_user.value.user ]]"
        loop: "[[  team | dict2items ]]"
        loop_control:
          loop_var: new_sliver_user
          label: "[[ new_sliver_user.value.user ]]"
      - name: "Install Sally the Sliver Siren"
        include_tasks: "[[ playbook_dir ]]/install/install-sally-the-sliver-siren.yml"