---
- name: Setup the lighthouse server
  gather_facts: true
  hosts: lighthouse
  become: true
  tasks:

  - name: Install Logstash on the host
    include_tasks: '{{ playbook_dir }}/install/install-logstash.yml'

  - name: Create the Logstash directory
    ansible.builtin.file:
      path: /opt/logstash
      state: directory

  - name: Create the Logstash runtime configuration directory
    ansible.builtin.file:
      path: /opt/logstash/logstash.d
      state: directory

  - name: Deploy the Logstash service configuration
    ansible.builtin.template:
      src: '{{ playbook_dir }}/../templates/elastic/logstash/logstash.yml.j2'
      dest: /etc/logstash/logstash.yml
      owner: logstash
      group: root
    
  - name: Deploy the Logstash runtime configurations
    ansible.builtin.template:
      src: "{{ item }}"
      dest: "/opt/logstash/{{ item | basename | regex_replace('\\.j2$', '') }}"
      owner: logstash
      group: root
    with_fileglob:
      - "{{ playbook_dir }}/../templates/elastic/logstash/logstash.d/*.j2"
      - "{{ playbook_dir }}/../templates/elastic/logstash/logstash.d/*.conf"

  - name: Enable and start Logstash
    ansible.builtin.service:
      name: logstash
      enabled: true
      state: restarted

  - name: Enable and Start UFW
    community.general.ufw:
      state: enabled
      