---
- name: Setup the Elasticsearh Server
  hosts: elastic
  become: true
  tasks:  

  - name: Install Logstash on the host
    include_tasks: '{{ playbook_dir }}/install/install-logstash.yml'

  - name: Modify Kibana to listen on all interfaces (port)
    ansible.builtin.replace:
      path: /etc/kibana/kibana.yml
      regex: ^#server.port
      replace: 'server.port: 5601'

  - name: Modify Kibana to listen on all interfaces (address)
    ansible.builtin.replace:
      path: /etc/kibana/kibana.yml
      regex: ^#server.host
      replace: 'server.host: "0.0.0.0"'

  - name: Load the service files
    ansible.builtin.service:
      state: reloaded
    # shell: |
    #   systemctl daemon-reload

  - name: Enable and start Elasticsearch
    ansible.builtin.service:
      name: elasticsearch
      enabled: true
      state: restarted

  - name: Enable and start Kibana
    ansible.builtin.service:
      name: kibana
      enabled: true
      state: restarted

  - name: Generate the Elastic enrollment token
    shell: |
      /usr/share/elasticsearch/bin/elasticsearch-create-enrollment-token -s kibana