---
- name: Setup the Categorization Server
  hosts: categorize
  become: true
  tasks:  

  - name: Verify UFW installed
    ansible.builtin.apt:
      name: ufw
      state: present

  - name: UFW Allow HTTP
    community.general.ufw:
      rule: allow
      proto: tcp
      port: 80
      comment: "Allow HTTP in"

  - name: UFW Allow HTTPS
    community.general.ufw:
      rule: allow
      proto: tcp
      port: 443
      comment: "Allow HTTPS in"

  - name: Install Apache2
    import_tasks: "{{ playbook_dir }}/install/install-apache.yml"

  - name: Install Certbot
    include_tasks: '{{ playbook_dir }}/install/install-certbot.yml'

  - name: Generate SSL Certificates for the domains
    include_tasks: '{{ playbook_dir }}/core/generate-ssl-certificates.yml'
  
  - name: Create the htaccess file for domain impersonation
    ansible.builtin.copy:
      dest: /var/www/html/.htaccess
      content: |
        RewriteEngine On
        RewriteRule ^.*$ https://{{ domain_to_impersonate }}/ [R,L]
    
  - name: Enable and Start UFW
    community.general.ufw:
      state: enabled
