---
- name: Setup the lighthouse server
  gather_facts: true
  hosts: lighthouse
  become: true
  tasks:

  - name: Install Logstash on the host
    include_tasks: '{{ playbook_dir }}/install/install-logstash.yml'

  - name: Create the Logstash directory
    ansible.builtin.file:
      path: /opt/logstash
      state: directory

  - name: Deploy the Logstash service configuration
    ansible.builtin.template:
      src: '{{ playbook_dir }}/../templates/elastic/logstash/logstash.yml.j2'
      dest: /etc/logstash/logstash.yml
      owner: logstash
      group: root
    
  - name: Deploy the Logstash runtime configuration
    ansible.builtin.template:
      src: '{{ playbook_dir }}/../templates/elastic/logstash/logstash.conf.j2'
      dest: /opt/logstash/logstash.conf
      owner: logstash
      group: root

  - name: Start the Logstash service
    shell: |
      systemctl stop logstash
      systemctl enable logstash --now

  - name: Enforce firewall rules
    include_tasks: "{{ playbook_dir }}/core/enforce-firewall-rules.yml"
      