---
- name: Setup the lighthouse server
  gather_facts: true
  hosts: lighthouse
  become: true
  tasks:

  - name: Install Logstash on the host
    include_tasks: '{{ playbook_dir }}/install/install-logstash.yml'

  - name: Enforce firewall rules
    include_tasks: "{{ playbook_dir }}/core/enforce-firewall-rules.yml"
      